"use client"

import './globals.css'
// import '../assets/css/styles.css'
import { Inter } from 'next/font/google'


import Header from '@/app/components/Header';
import Footer from '@/app/components/Footer';
import Data from '../json/landingPage.json';

const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
          {children}
        <Footer />
      </body>
    </html>
  )
}
